version: '3'

services: 
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    networks:
      - desafio2-network
    depends_on:
      - node

  node:
    build:
      context: ./node
    container_name: node
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh
    networks:
      - desafio2-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    # command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - mysql_data:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - desafio2-network

volumes:
  mysql_data:
    driver: local

networks: 
  desafio2-network:
    driver: bridge      